Repository forestryio/create-static-site, pull requests merged in 2018-02, with the labels that each got.

#24 Node 6 support
  packages/static-scripts/config/paths.js
  packages/static-scripts/config/static-scripts.config.js
  packages/static-scripts/config/webpack.config.js
  packages/static-scripts/scripts/init.js
Labels: tag: bug fix

#26 Fix Jekyll reference to Hugo.
  packages/static-scripts/templates/hugo/site/content/posts/example.md
Labels: package: static-scripts, tag: documentation

#25 display link to survey after user runs `eject`
  packages/static-scripts/scripts/eject.js
Labels: tag: documentation
